name: "Concourse CI"
description: |
  Concourse CI including a preset, autoconfigured vault
version: 3.6.0.1
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://concourse.ci/
