name: "Concourse CI Standalone Worker"
description: |
version: 3.8.0.1
  Concourse CI Standalone Worker
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://concourse.ci/
