version: "2"

services:
  config:
    labels:
      io.rancher.container.pull_image: always
    image: eugenmayer/concourse-configurator
    volumes:
      - concourse-keys-web:/concourse-keys/web
      - concourse-keys-worker:/concourse-keys/worker
      - vault-server-config:/vault/server
      - vault-client-config:/vault/concourse
    restart: unless-stopped
    environment:
      VAULT_ENABLED: 1
      VAULT_DO_AUTOCONFIGURE: 1
  vault:
     restart: unless-stopped # required so that it retries until conocurse-db comes up
     image: vault:0.9.0
     cap_add:
       - IPC_LOCK
     depends_on:
       - config
     # there should be no need to open this port to the outer world since we configure using config
     # still, of course this can be enabled if needed
     #ports:
     #  - 8200:8200
     volumes:
       - vault-server-config:/vault/config
       - vault-server-data:/vault/file
     command: vault server -config /vault/config/vault.hcl

  db:
    image: postgres:10.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  web:
    labels:
      io.rancher.container.pull_image: always
    image: concourse/concourse:3.7.0
    command: web --vault-ca-cert /vault/client/server.crt
    depends_on:
      - config
      - db
      - vault
    volumes:
      - concourse-keys-web:/concourse-keys
      - vault-client-config:/vault/client
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${ADMIN_USER}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${ADMIN_PASSWORD}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: ${DB_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${DB_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${DB_NAME}

      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_TLS_INSECURE_SKIP_VERIFY: "true"
      CONCOURSE_VAULT_AUTH_BACKEND: cert
      CONCOURSE_VAULT_PATH_PREFIX: /secret/concourse
      # those keys are generated by the config container
      CONCOURSE_VAULT_CLIENT_CERT: /vault/client/cert.pem
      CONCOURSE_VAULT_CLIENT_KEY: /vault/client/key.pem
  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  worker:
    labels:
      io.rancher.container.pull_image: always
    image: eugenmayer/concourse-worker-solid:3.7.0
    privileged: true
    depends_on:
      - config
      - web
    volumes:
      - concourse-keys-worker:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: web
      CONCOURSE_GARDEN_NETWORK_POOL: ${CONCOURSE_GARDEN_NETWORK_POOL}
      CONCOURSE_BAGGAGECLAIM_DRIVER: ${CONCOURSE_BAGGAGECLAIM_DRIVER}
      CONCOURSE_BAGGAGECLAIM_LOG_LEVEL: ${CONCOURSE_BAGGAGECLAIM_LOG_LEVEL}
      CONCOURSE_GARDEN_LOG_LEVEL: ${CONCOURSE_GARDEN_LOG_LEVEL}
volumes:
  pgdata:
    driver: local
  concourse-keys-web:
    driver: local
  concourse-keys-worker:
    driver: local
  vault-server-data:
    driver: local
  vault-server-config:
    driver: local
  vault-client-config:
    driver: local

