name: "Concourse CI Cluster"
description: |
  Concourse CI Cluster version with spreaded workers
version: 3.8.0.10
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: http://concourse.ci/
