name: "whoami"
description: |
  Test-Service: Returns all request headers and fields for debugging. E.g. for checking a proxy or loadbalancer
version: 0.4
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://hub.docker.com/r/eugenmayer
