version: '2'
volumes:
  ${DATA}:
    driver: ${NEXUS_STORAGE_DRIVER}
services:
  nexus:
    image: sonatype/nexus3:3.9.0-01
      volumes:
        - ${DATA}:/nexus-data
      labels:
        io.rancher.container.create_agent: 'true'
        io.rancher.container.agent.role: 'environment'
