name: "whats my ip"
description: |
  Returns your IP as static payload - a very simple golan programm for that and only that ( use with dyndns ), Port is exposed on 8080
version: 0.2
category: Applications
maintainer: "Eugen Mayer <eugen.mayer@kontextwork.de>"
projectURL: https://hub.docker.com/r/eugenmayer/whatsmyip/
